### ISSUE TITLE
gallery set contains the videos from the same camera of the query video?

### ISSUE THREAD

**Issue by YurongYou** [liangzheng06/MARS-evaluation#3]
Hi!

From the evaluation protocol part of your paper, it is said that

> query and gallery are captured by diﬀerent cameras.

But from
https://github.com/liangzheng06/MARS-evaluation/blob/3a91bbc762fad7629fecde8c53e170742d3700f9/utils/evaluation_mars.m#L12-L18

it does not mark the feature of persons of a different label but with the same camera as ``junk'', which will make the computed CMC lower than using the setting of cross-camera search.

**Comment by liangzheng06** [comment]
Hi, 

What you suggest is actually correct for evaluation. It accords precisely to what I described in my paper. 

But in the current evaluation, I would rather keep the persons in the same query camera in the database. It helps simplify the code and enlarges the actual database. 

I think both practices are acceptable.

**Comment by YurongYou** [comment]
Yes, I agree. Thanks for your prompt reply!

**Comment by liangzheng06** [comment]
Sure. I would suggest you use the provided evaluation package so that your results are comparable with other people.
